name: Release

on:
  release:
    types: [created]
# on:
#   push:
#     branches:
#       - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    env:
      CI: true
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: |
          npm install -g npm@latest
          npm i
          npm i --no-save eslint

      - name: static checks
        run: |
          npm run lint

      - name: build
        run: |
          npm run build

      - name: test
        run: |
          npm run testb
          npm run test:fetch

      # And finally... publish it!  Note that we create the .npmrc file
      # "just in time" so that `npm publish` can get the auth token from the
      # environment
      - name: publish
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          npm publish --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
